### PR TITLE
`eventCallbacks` fixes

### PR DESCRIPTION
**Pull request by agurtovoy**
- Fix "Cannot read property 'ready' of undefined" in `getCallback`
- Fix `removeCallback` bug w/ removing unrelated event callback in certain cases
- Rebuild `froogaloop.min.js`

### CODE REVIEW

**Comment by joaoreynolds** [comment]
This is a great fix. I can't believe they haven't merged this yet.

**Comment by bgeisel1** [comment]
I'm not sure why issue #19 has been closed, but it is still a bug until this pull request is merged. We tested it here and it fixed the problem we were having when the same video appears twice on a page.

**Comment by BB-000** [comment]
+1 ,  issue #19 still happens to me without this

**Comment by melv-n** [comment]
+1

**Pull request closed without merging**
